# Generated by Django 5.1.7 on 2025-04-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="product",
            name="network_node",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                help_text="Укажите модель продукта",
                max_length=255,
                verbose_name="Модель продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Укажите название продукта",
                max_length=255,
                verbose_name="Название продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                help_text="Укажите дату выхода продукта на рынок",
                verbose_name="Дата выхода продукта на рынок",
            ),
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите email", max_length=100, verbose_name="Почта"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Укажите страну",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Укажите город", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Укажите улицу", max_length=100, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="Укажите номер дома",
                        max_length=10,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        default=0,
                        verbose_name="Уровень сети",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="electronics.enterprise",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ManyToManyField(
                to="electronics.enterprise", verbose_name="Поставщик"
            ),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="NetworkNode",
        ),
    ]
